
function xeng_core_config(this_block)

  % Revision History:
  %
  %   02-Aug-2012  (18:11 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     /home/rprimian/git/design_files/xeng_core.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('xeng_core');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  %this_block.tagAsCombinational;


  this_block.addSimulinkInport('newacc');
  this_block.addSimulinkInport('i0_pol0');
  this_block.addSimulinkInport('i0_pol1');
  this_block.addSimulinkInport('i1_pol0');
  this_block.addSimulinkInport('i1_pol1');

  this_block.addSimulinkOutport('bin');
  this_block.addSimulinkOutport('rdy');
  this_block.addSimulinkOutport('p0xp0');
  this_block.addSimulinkOutport('p0xp1');
  this_block.addSimulinkOutport('p1xp0');
  this_block.addSimulinkOutport('p1xp1');
  
  bin_port = this_block.port('bin');
  bin_port.setType('UFix_11_0');
  p0xp0_port = this_block.port('p0xp0');
  p0xp0_port.setType('UFix_64_0');
  p0xp1_port = this_block.port('p0xp1');
  p0xp1_port.setType('UFix_64_0');
  p1xp0_port = this_block.port('p1xp0');
  p1xp0_port.setType('UFix_64_0');
  p1xp1_port = this_block.port('p1xp1');
  p1xp1_port.setType('UFix_64_0');
  rdy_port = this_block.port('rdy');
  rdy_port.setType('Bool');
  rdy_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('i0_pol0').width ~= 8);
      this_block.setError('Input data type for port "i0_pol0" must have width=8.');
    end

    if (this_block.port('i0_pol1').width ~= 8);
      this_block.setError('Input data type for port "i0_pol1" must have width=8.');
    end

    if (this_block.port('i1_pol0').width ~= 8);
      this_block.setError('Input data type for port "i1_pol0" must have width=8.');
    end

    if (this_block.port('i1_pol1').width ~= 8);
      this_block.setError('Input data type for port "i1_pol1" must have width=8.');
    end

    if (this_block.port('newacc').width ~= 1);
      this_block.setError('Input data type for port "newacc" must have width=1.');
    end

    this_block.port('newacc').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk_1','ce_1')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('xeng_core.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

